 ptxas -arch=sm_70 -m64  "main.ptx"  -o "main.sm_70.cubin" 
 fatbinary --create="main.fatbin" -64 "--image=profile=sm_70,file=main.sm_70.cubin" "--image=profile=compute_70,file=main.ptx" --embedded-fatbin="main.fatbin.c" 
 gcc -E -x c++ -D__CUDACC__ -D__NVCC__  -O3 -I"../../include/mem_alloc" "-I/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=243 -include "cuda_runtime.h" -m64 "main.cu" > "main.cpp4.ii" 
 cudafe++ --c++14 --gnu_version=70500 --allow_managed  --m64 --parse_templates --gen_c_file_name "main.cudafe1.cpp" --stub_file_name "main.cudafe1.stub.c" --module_id_file_name "main.module_id" "main.cpp4.ii" 
 gcc -D__CUDA_ARCH__=700 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -O3 -I"../../include/mem_alloc" "-I/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/../targets/x86_64-linux/include"   -m64 -o "main.o" "main.cudafe1.cpp" 
 nvlink --arch=sm_70 --register-link-binaries="main_COAL_dlink.reg.c"  -m64   "-L/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/../targets/x86_64-linux/lib/stubs" "-L/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/../targets/x86_64-linux/lib" -cpu-arch=X86_64 "main.o"  -lcudadevrt  -o "main_COAL_dlink.sm_70.cubin"
 fatbinary --create="main_COAL_dlink.fatbin" -64 -link "--image=profile=sm_70,file=main_COAL_dlink.sm_70.cubin" --embedded-fatbin="main_COAL_dlink.fatbin.c" 
 gcc -c -x c++ -DFATBINFILE="\"main_COAL_dlink.fatbin.c\"" -DREGISTERLINKBINARYFILE="\"main_COAL_dlink.reg.c\"" -I. -D__NV_EXTRA_INITIALIZATION= -D__NV_EXTRA_FINALIZATION= -D__CUDA_INCLUDE_COMPILER_INTERNAL_HEADERS__  -O3 -I"../../include/mem_alloc" "-I/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/../targets/x86_64-linux/include"    -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=243 -m64 -o "main_COAL_dlink.o" "/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/crt/link.stub" 
 g++ -O3 -m64 -o "./main_COAL" -Wl,--start-group "main_COAL_dlink.o" "main.o"   "-L/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/../targets/x86_64-linux/lib/stubs" "-L/home/tgrogers-raid/a/zhan2308/cuda-10.1/tools//bin/../targets/x86_64-linux/lib" -lcudadevrt  -lcudart_static  -lrt -lpthread  -ldl  -Wl,--end-group 
